### ISSUE TITLE
Cannot retrieve data

### ISSUE THREAD

**Issue by karask** [coinspark/python-OP_RETURN#6]
I did a quick test of the cli tools. I stored some data:

$ python store-OP_RETURN.py "Test kk message!" 1
TxIDs: b4c9efa9e53c586b4ead18a802b98c647c3774900e3dea62d676db11e5f4cca4
Ref: 1064270-051636

...and then tried to retrieve using the reference but I got the following error:

$ python retrieve-OP_RETURN.py 1064270-051636 1
Traceback (most recent call last):
  File "retrieve-OP_RETURN.py", line 43, in <module>
    results=OP_RETURN_retrieve(ref, 1, testnet)
  File "/home/user/scripts/python/python-OP_RETURN/OP_RETURN.py", line 211, in OP_RETURN_retrieve
    txns=OP_RETURN_get_block_txns(height, testnet) # if block, get all fully unpacked
  File "/home/user/scripts/python/python-OP_RETURN/OP_RETURN.py", line 401, in OP_RETURN_get_block_txns
    block=OP_RETURN_unpack_block(raw_block['block'])
  File "/home/user/scripts/python/python-OP_RETURN/OP_RETURN.py", line 623, in OP_RETURN_unpack_block
    transaction=OP_RETURN_unpack_txn_buffer(buffer)
  File "/home/user/scripts/python/python-OP_RETURN/OP_RETURN.py", line 663, in OP_RETURN_unpack_txn_buffer
    input['sequence']=buffer.shift_unpack(4, '<L')
  File "/home/user/scripts/python/python-OP_RETURN/OP_RETURN.py", line 785, in shift_unpack
    unpack=struct.unpack(format, self.shift(chars))
struct.error: unpack requires a bytes object of length 4

**Comment by gidgreen** [comment]
It looks like the library didn't successfully get a block from the Bitcoin Core process. If you keep seeing this upon retrying, it's worth going in to debug where things are going wrong. Perhaps the node was still catching up with the blockchain? The transaction itself appears to be in the testnet blockchain.

**Comment by karask** [comment]
Yes, I checked the transaction and it is fine (store worked as expected). My testnet blockchain is uptodate and tried to retrieve again after several confirmations (just in case). I won't necessarily use it... just wanted to know what is available. If I have some more time I will investigate further.

Should I assume that you tried to retrieve the ref and it worked for you?

**Comment by gidgreen** [comment]
We didn't try the ref here, no, just checked in the blockchain.

**Comment by crypto-perry** [comment]
I found the fix for this it was a padding problem. Not sure if this project is still supported though. Are you still interested in this? I am planning to use your code to implement a commit reveal scheme in Bitcoin. Any chance you know of similar projects? What are other use cases for OP_RETURN
